/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/artifacts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Artifact */
        get: operations["download_artifact_api_v1_runs__run_id__artifacts__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_api_v1_runs__run_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence Item */
        get: operations["get_evidence_item_api_v1_runs__run_id__evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Papers */
        get: operations["get_papers_api_v1_runs__run_id__papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/papers/{paper_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper Analysis */
        get: operations["get_paper_analysis_api_v1_runs__run_id__papers__paper_id__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_v1_runs__run_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CheckedClaim */
        CheckedClaim: {
            /** Evidence Ids */
            evidence_ids: string[];
            /**
             * Support Status
             * @enum {string}
             */
            support_status: "supported" | "weakly_supported" | "unsupported";
            /** Text */
            text: string;
        };
        /** CheckedFinding */
        CheckedFinding: {
            /** Evidence Ids */
            evidence_ids: string[];
            /**
             * Support Status
             * @enum {string}
             */
            support_status: "supported" | "weakly_supported" | "unsupported";
            /** Text */
            text: string;
        };
        /** CheckedPaperAnalysis */
        CheckedPaperAnalysis: {
            /** Contributions */
            contributions?: components["schemas"]["CheckedFinding"][];
            /** Experiments */
            experiments?: components["schemas"]["CheckedFinding"][];
            /** Limitations */
            limitations?: components["schemas"]["CheckedFinding"][];
            /** Methods */
            methods?: components["schemas"]["CheckedFinding"][];
            /** Paper Id */
            paper_id: string;
            /** Results */
            results?: components["schemas"]["CheckedFinding"][];
        };
        /** CheckedSurveyReport */
        CheckedSurveyReport: {
            /** Comparisons */
            comparisons?: components["schemas"]["CheckedClaim"][];
            /** Key Findings */
            key_findings?: components["schemas"]["CheckedClaim"][];
            /** Limitations */
            limitations?: components["schemas"]["CheckedClaim"][];
            /** Method Taxonomy */
            method_taxonomy?: components["schemas"]["CheckedClaim"][];
            /** Open Questions */
            open_questions?: components["schemas"]["CheckedClaim"][];
            /** Question */
            question: string;
            /** Rejected Critical Claims */
            rejected_critical_claims?: components["schemas"]["RejectedCriticalClaim"][];
            /** Tldr Claims */
            tldr_claims?: components["schemas"]["CheckedClaim"][];
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /**
             * Content Mode
             * @enum {string}
             */
            content_mode: "pdf_preferred" | "abstract_only";
            /** Paper Limit */
            paper_limit: number;
            /** Question */
            question: string;
            retrieval: components["schemas"]["RetrievalRequest"];
        };
        /** DocumentRecord */
        DocumentRecord: {
            /** Content Sha256 */
            content_sha256: string;
            /**
             * Content Source
             * @enum {string}
             */
            content_source: "pdf" | "abstract";
            /** Fallback Code */
            fallback_code?: string | null;
            /** Page Count */
            page_count: number;
            /** Paper Id */
            paper_id: string;
            /** Warnings */
            warnings?: string[];
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** EvidenceList */
        EvidenceList: {
            /** Items */
            items: components["schemas"]["EvidenceView"][];
        };
        /** EvidenceSource */
        EvidenceSource: {
            /** Content Source */
            content_source?: ("pdf" | "abstract") | null;
            /** Fallback Code */
            fallback_code?: string | null;
            /** Pdf Url */
            pdf_url?: string | null;
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
        };
        /** EvidenceView */
        EvidenceView: {
            /** Chunk Id */
            chunk_id: string;
            /** Claim Type */
            claim_type: string;
            /** Evidence Id */
            evidence_id: string;
            /** Page */
            page?: number | null;
            /** Paper Id */
            paper_id: string;
            /** Quote */
            quote: string;
            /** Relevance Score */
            relevance_score: number;
            /** Section */
            section?: string | null;
            source: components["schemas"]["EvidenceSource"];
        };
        /** ManifestProjection */
        ManifestProjection: {
            /** Component Versions */
            component_versions: {
                [key: string]: string;
            };
            counts: components["schemas"]["RunCounts"];
            /** Degradations */
            degradations: components["schemas"]["RunIssue"][];
            /** Errors */
            errors: components["schemas"]["RunIssue"][];
            /** Retrieval Outcomes */
            retrieval_outcomes: components["schemas"]["RetrievalRecord"][];
            settings: components["schemas"]["SafeRunSettings"];
            /** Stage Elapsed Seconds */
            stage_elapsed_seconds: {
                [key: string]: number;
            };
            usage: components["schemas"]["UsageTotals"];
        };
        /** Paper */
        Paper: {
            /**
             * Abstract
             * @default
             */
            abstract: string;
            /** Authors */
            authors?: string[];
            /** Citation Count */
            citation_count?: number | null;
            /** Paper Id */
            paper_id: string;
            /** Pdf Url */
            pdf_url?: string | null;
            /** Source */
            source: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Year */
            year?: number | null;
        };
        /** PaperAnalysisResponse */
        PaperAnalysisResponse: {
            analysis: components["schemas"]["CheckedPaperAnalysis"];
            document: components["schemas"]["DocumentRecord"] | null;
            paper: components["schemas"]["Paper"];
            /**
             * Run Id
             * Format: uuid4
             */
            run_id: string;
        };
        /** PaperList */
        PaperList: {
            /** Items */
            items: components["schemas"]["PaperSummary"][];
        };
        /** PaperSummary */
        PaperSummary: {
            /**
             * Abstract
             * @default
             */
            abstract: string;
            /** Analysis Available */
            analysis_available: boolean;
            /** Authors */
            authors?: string[];
            /** Citation Count */
            citation_count?: number | null;
            document: components["schemas"]["DocumentRecord"] | null;
            /** Evidence Count */
            evidence_count: number;
            /** Paper Id */
            paper_id: string;
            /** Pdf Url */
            pdf_url?: string | null;
            /** Source */
            source: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Year */
            year?: number | null;
        };
        /** RejectedCriticalClaim */
        RejectedCriticalClaim: {
            /** Evidence Ids */
            evidence_ids: string[];
            /**
             * Source Section
             * @enum {string}
             */
            source_section: "tldr_claims" | "key_findings";
            /**
             * Support Status
             * @enum {string}
             */
            support_status: "supported" | "weakly_supported" | "unsupported";
            /** Text */
            text: string;
        };
        /** ReportResponse */
        ReportResponse: {
            /** Degradations */
            degradations: components["schemas"]["RunIssue"][];
            /** Markdown */
            markdown: string;
            report: components["schemas"]["CheckedSurveyReport"];
            /**
             * Run Id
             * Format: uuid4
             */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "completed_with_degradation";
        };
        /** RetrievalRecord */
        RetrievalRecord: {
            /**
             * Actual Mode
             * @enum {string}
             */
            actual_mode: "lexical" | "hybrid";
            /** Degradation Code */
            degradation_code?: string | null;
            /** Degraded */
            degraded: boolean;
            /** Paper Id */
            paper_id: string;
            /**
             * Requested Mode
             * @enum {string}
             */
            requested_mode: "auto" | "lexical" | "hybrid";
        };
        /** RetrievalRequest */
        RetrievalRequest: {
            /** Analysis Evidence Per Paper */
            analysis_evidence_per_paper: number;
            /** Candidate K */
            candidate_k: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "auto" | "lexical" | "hybrid";
            /** Rrf K */
            rrf_k: number;
            /** Top K */
            top_k: number;
        };
        /** RunCounts */
        RunCounts: {
            /** Abstract Documents */
            abstract_documents: number;
            /** Evidence Items */
            evidence_items: number;
            /** Excluded Papers */
            excluded_papers: number;
            /** Explicit Abstract Documents */
            explicit_abstract_documents: number;
            /** Pdf Documents */
            pdf_documents: number;
            /** Pdf Fallback Documents */
            pdf_fallback_documents: number;
            /** Selected Papers */
            selected_papers: number;
            /** Successful Analyses */
            successful_analyses: number;
        };
        /** RunDetail */
        RunDetail: {
            /** Artifact Run Id */
            artifact_run_id: string | null;
            /** Available Artifacts */
            available_artifacts: ("papers.json" | "documents.json" | "evidence.json" | "analyses.json" | "report.json" | "report.md" | "run_manifest.json" | "logs.jsonl")[];
            /**
             * Content Mode
             * @enum {string}
             */
            content_mode: "pdf_preferred" | "abstract_only";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Demo */
            demo: boolean;
            /** Finished At */
            finished_at: string | null;
            /** Has Report */
            has_report: boolean;
            /**
             * Id
             * Format: uuid4
             */
            id: string;
            manifest: components["schemas"]["ManifestProjection"] | null;
            /**
             * Origin
             * @enum {string}
             */
            origin: "live" | "bundled_demo";
            /** Paper Limit */
            paper_limit: number;
            /**
             * Phase
             * @enum {string}
             */
            phase: "queued" | "initializing" | "search" | "acquisition" | "chunking" | "retrieval" | "analysis" | "synthesis" | "citation_check" | "publishing" | "terminal";
            progress: components["schemas"]["RunProgress"];
            /** Question */
            question: string;
            retrieval: components["schemas"]["RetrievalRequest"];
            /** Started At */
            started_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "completed_with_degradation" | "failed" | "interrupted";
        };
        /** RunIssue */
        RunIssue: {
            /** Code */
            code: string;
            /** Message */
            message?: string | null;
            /** Paper Id */
            paper_id?: string | null;
            /** Stage */
            stage: string;
        };
        /** RunList */
        RunList: {
            /** Items */
            items: components["schemas"]["RunSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** RunProgress */
        RunProgress: {
            /** Completed Units */
            completed_units?: number | null;
            /** Paper Id */
            paper_id?: string | null;
            /** Total Units */
            total_units?: number | null;
        };
        /** RunSummary */
        RunSummary: {
            /** Artifact Run Id */
            artifact_run_id: string | null;
            /**
             * Content Mode
             * @enum {string}
             */
            content_mode: "pdf_preferred" | "abstract_only";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Demo */
            demo: boolean;
            /** Finished At */
            finished_at: string | null;
            /** Has Report */
            has_report: boolean;
            /**
             * Id
             * Format: uuid4
             */
            id: string;
            /**
             * Origin
             * @enum {string}
             */
            origin: "live" | "bundled_demo";
            /** Paper Limit */
            paper_limit: number;
            /**
             * Phase
             * @enum {string}
             */
            phase: "queued" | "initializing" | "search" | "acquisition" | "chunking" | "retrieval" | "analysis" | "synthesis" | "citation_check" | "publishing" | "terminal";
            progress: components["schemas"]["RunProgress"];
            /** Question */
            question: string;
            retrieval: components["schemas"]["RetrievalRequest"];
            /** Started At */
            started_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "completed_with_degradation" | "failed" | "interrupted";
        };
        /** SafeRunSettings */
        SafeRunSettings: {
            /** Analysis Evidence Per Paper */
            analysis_evidence_per_paper: number;
            /** Chunk Max Words */
            chunk_max_words: number;
            /** Chunk Overlap Words */
            chunk_overlap_words: number;
            /** Embedding Model */
            embedding_model: string;
            /** Generation Endpoint Host */
            generation_endpoint_host: string;
            /** Generation Model */
            generation_model: string;
            /**
             * Generation Provider
             * @constant
             */
            generation_provider: "dashscope";
            /** Generation Timeout Seconds */
            generation_timeout_seconds: number;
            /** Pdf Download Timeout Seconds */
            pdf_download_timeout_seconds: number;
            /** Pdf Max Bytes */
            pdf_max_bytes: number;
            /** Pdf Max Pages */
            pdf_max_pages: number;
            /**
             * Retrieval Mode
             * @enum {string}
             */
            retrieval_mode: "auto" | "lexical" | "hybrid";
        };
        /** UsageTotals */
        UsageTotals: {
            /** Completion Tokens */
            completion_tokens?: number | null;
            /** Http Attempts */
            http_attempts: number;
            /** Operations */
            operations: number;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunList"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    download_artifact_api_v1_runs__run_id__artifacts__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_evidence_api_v1_runs__run_id__evidence_get: {
        parameters: {
            query?: {
                paper_id?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceList"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_evidence_item_api_v1_runs__run_id__evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_papers_api_v1_runs__run_id__papers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperList"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_paper_analysis_api_v1_runs__run_id__papers__paper_id__analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperAnalysisResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_report_api_v1_runs__run_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
